#pragma once

// Dumped with Dumper-7!

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass Lib_Audio.Lib_Audio_C
class ULib_Audio_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass()
	{
		static class UClass* Clss = UObject::FindClassFast("Lib_Audio_C");
		return Clss;
	}

	void GetMusicManager(class UObject* In__WorldContext, class UBP_MusicManager_C** InAsBP_Music_Manager, class UGameInstance* InCallFunc_GetGameInstance_ReturnValue, class UValeriaGameInstance* InK2Node_DynamicCast_AsValeria_Game_Instance, bool InK2Node_DynamicCast_bSuccess, class UMusicManager* InCallFunc_GetMusicManager_ReturnValue, class UBP_MusicManager_C* InK2Node_DynamicCast_AsBP_Music_Manager, bool InK2Node_DynamicCast_bSuccess_1);
	void Try_to_Propagate_Rtpcs(class AActor* InActor, class UAkComponent* InAkComponent, class UObject* In__WorldContext, bool* InSuccess, class UComp_RtpcTracker_C* InTracker, bool InCallFunc_IsValid_ReturnValue, bool InCallFunc_IsValid_ReturnValue_1, class UComp_RtpcTracker_C* InCallFunc_GetComponentByClass_ReturnValue, bool InCallFunc_IsValid_ReturnValue_2);
	void AkGetComponent(class USceneComponent* InAttachToComponent, class FName InAttachPointName, const struct FVector& InLocation, enum class EAttachLocation InLocationType, bool InbAutoDestroy, class UObject* In__WorldContext, bool* InComponentCreated, class UAkComponent** InAkComponent, bool InCallFunc_VAkGetComponent_ComponentCreated, class UAkComponent* InCallFunc_VAkGetComponent_ReturnValue);
	void AkExecuteActionOnPlayingID(enum class EAkActionOnEventType InActionType, int32 InPlayingID, int32 InTransitionDuration, enum class EAkCurveInterpolation InFadeCurve, class UObject* In__WorldContext);
	void IsInside(const struct FVector& InLocation, class UObject* In__WorldContext, bool* InIsInside, bool InInside, bool InTemp_bool_True_if_break_was_hit_Variable, class UAkRoomComponent* InCallFunc_GetAkAudioRoomAtLocation_HighestPriorityRoom, TArray<class UAkRoomComponent*>& InCallFunc_GetAkAudioRoomAtLocation_AllRooms, bool InCallFunc_IsValid_ReturnValue, class AActor* InCallFunc_GetOwner_ReturnValue, class AAkSpatialAudioVolume* InK2Node_DynamicCast_AsAk_Spatial_Audio_Volume, bool InK2Node_DynamicCast_bSuccess, TArray<class UComp_CV_Local_RTPC_C*>& InCallFunc_K2_GetComponentsByClass_ReturnValue, bool InCallFunc_IsValid_ReturnValue_1, int32 InCallFunc_Array_Length_ReturnValue, bool InCallFunc_Not_PreBool_ReturnValue, int32 InTemp_int_Array_Index_Variable, class UComp_CV_Local_RTPC_C* InCallFunc_Array_Get_Item, bool InCallFunc_EqualEqual_DoubleDouble_ReturnValue, bool InCallFunc_EqualEqual_ObjectObject_ReturnValue, bool InCallFunc_BooleanAND_ReturnValue, int32 InTemp_int_Loop_Counter_Variable, bool InCallFunc_Less_IntInt_ReturnValue, int32 InCallFunc_Add_IntInt_ReturnValue, bool InCallFunc_BooleanAND_ReturnValue_1);
	void IsWet(const struct FVector& InLocation, class UObject* In__WorldContext, bool* InIsWet, class UValeriaWeather* InCallFunc_GetWorldSubsystem_ReturnValue, bool InCallFunc_IsInside_IsInside, const struct FWeatherStateProperties& InCallFunc_GetCurrentWorldWeatherState_ReturnValue, bool InCallFunc_HasTag_ReturnValue);
	void AkCulledAssignAndStart(class UAkAudioEvent* InAkEvent, class UAkCulledComponent* InAkCulledComponent, class UObject* In__WorldContext, double InLocallyControlled, bool InCallFunc_IsDedicatedServer_ReturnValue, bool InCallFunc_IsValid_ReturnValue);
	void GetAkAudioRoomAtLocation(const struct FVector& InLocation, class UObject* In__WorldContext, class UAkRoomComponent** InHighestPriorityRoom, TArray<class UAkRoomComponent*>* InAllRooms, const TArray<class UAkRoomComponent*>& InLRoomComponents, class UAkRoomComponent* InLHighestPriorityRoom, double InLHighestPriority, int32 InTemp_int_Loop_Counter_Variable, int32 InTemp_int_Loop_Counter_Variable_1, int32 InCallFunc_Add_IntInt_ReturnValue, int32 InCallFunc_Add_IntInt_ReturnValue_1, int32 InTemp_int_Loop_Counter_Variable_2, int32 InCallFunc_Add_IntInt_ReturnValue_2, int32 InTemp_int_Array_Index_Variable, int32 InTemp_int_Array_Index_Variable_1, int32 InTemp_int_Array_Index_Variable_2, int32 InTemp_int_Loop_Counter_Variable_3, int32 InCallFunc_Add_IntInt_ReturnValue_3, int32 InTemp_int_Array_Index_Variable_3, class UAkRoomComponent* InCallFunc_Array_Get_Item, int32 InCallFunc_Array_Length_ReturnValue, bool InCallFunc_Less_IntInt_ReturnValue, TArray<class AActor*>& InTemp_object_Variable, TArray<class AActor*>& InTemp_object_Variable_1, TArray<enum class EObjectTypeQuery>& InK2Node_MakeArray_Array, TArray<class UPrimitiveComponent*>& InCallFunc_SphereOverlapComponents_OutComponents, bool InCallFunc_SphereOverlapComponents_ReturnValue, bool InCallFunc_Greater_DoubleDouble_ReturnValue, class UPrimitiveComponent* InCallFunc_Array_Get_Item_1, TArray<class USceneComponent*>& InCallFunc_GetChildrenComponents_Children, int32 InCallFunc_Array_Length_ReturnValue_1, class USceneComponent* InCallFunc_Array_Get_Item_2, bool InCallFunc_Less_IntInt_ReturnValue_1, class UAkRoomComponent* InK2Node_DynamicCast_AsAk_Room_Component, bool InK2Node_DynamicCast_bSuccess, int32 InCallFunc_Array_AddUnique_ReturnValue, int32 InCallFunc_Array_Length_ReturnValue_2, TArray<class AActor*>& InCallFunc_SphereOverlapActors_OutActors, bool InCallFunc_SphereOverlapActors_ReturnValue, bool InCallFunc_Less_IntInt_ReturnValue_2, class AActor* InCallFunc_Array_Get_Item_3, class AValeriaSpatialAudioVolume* InK2Node_DynamicCast_AsValeria_Spatial_Audio_Volume, bool InK2Node_DynamicCast_bSuccess_1, int32 InCallFunc_Array_Length_ReturnValue_3, bool InCallFunc_Less_IntInt_ReturnValue_3, int32 InCallFunc_Array_AddUnique_ReturnValue_1, double InCallFunc_Greater_DoubleDouble_A_ImplicitCast, double InK2Node_VariableSet_LHighestPriority_ImplicitCast);
	int32 PlayTempBeep(bool InGlobal, const struct FVector& InLocation, class UObject* In__WorldContext, bool InCallFunc_BuildIsShipping_ReturnValue, class UAkComponent* InCallFunc_AkEventLocation_AkComponent, int32 InCallFunc_AkEventLocation_Playing_ID, int32 InCallFunc_AkEventGlobal_ReturnValue);
	void LoadAudioUserSettings(class UObject* In__WorldContext, class UAkStateValue* InTemp_object_Variable, class UAkStateValue* InTemp_object_Variable_1, class UAkStateValue* InTemp_object_Variable_2, enum class EAudioMixProfiles InTemp_byte_Variable, class UValeriaGameUserSettings* InCallFunc_GetValeriaGameUserSettings_ReturnValue, bool InCallFunc_IsValid_ReturnValue, class UAkStateValue* InK2Node_Select_Default, double InCallFunc_AkSetRTPC_Value_ImplicitCast, double InCallFunc_AkSetRTPC_Value_ImplicitCast_1, double InCallFunc_AkSetRTPC_Value_ImplicitCast_2, double InCallFunc_AkSetRTPC_Value_ImplicitCast_3);
	void Ak_Music_Switch(class UAkSwitchValue* InSwitchValue, bool InIgnoreTimeOfDay, class UObject* In__WorldContext, bool InCallFunc_IsDedicatedServer_ReturnValue, class APlayerController* InCallFunc_GetPlayerController_ReturnValue, class APawn* InCallFunc_K2_GetPawn_ReturnValue, class UBP_MusicManager_C* InCallFunc_GetMusicManager_AsBP_Music_Manager, bool InCallFunc_IsValid_ReturnValue, bool InCallFunc_IsValid_ReturnValue_1, class UComp_Listener_Padding_C* InCallFunc_GetComponentByClass_ReturnValue, bool InCallFunc_IsValid_ReturnValue_2, bool InCallFunc_Not_PreBool_ReturnValue);
	void FindClosestVector(TArray<struct FVector>& InInVectors, const struct FVector& InReferencePoint, class UObject* In__WorldContext, struct FVector* InClosestVector, int32* InIndex, double InIterateDistance, int32 InClosestInd, const struct FVector& InClosestVect, double InDistance, int32 InTemp_int_Array_Index_Variable, int32 InCallFunc_Array_Length_ReturnValue, const struct FVector& InCallFunc_Array_Get_Item, int32 InTemp_int_Loop_Counter_Variable, bool InCallFunc_Less_IntInt_ReturnValue, int32 InCallFunc_Add_IntInt_ReturnValue, bool InCallFunc_Less_DoubleDouble_ReturnValue, double InCallFunc_Vector_Distance_ReturnValue);
	void GetDopplerPitchMultiplier(class AActor* InListener, class AActor* InObject, double InDopplerIntensity, class UObject* In__WorldContext, double* InPitchMultiplier, double InFinalPitchScale, double InPitchScale, double InDopplerPitchScale, double InListenerVelocityMagnitude, double InSourceVelocityMagnitude, double InCallFunc_Divide_DoubleDouble_ReturnValue, double InCallFunc_Subtract_DoubleDouble_ReturnValue, double InCallFunc_Subtract_DoubleDouble_ReturnValue_1, double InCallFunc_Multiply_DoubleDouble_ReturnValue, double InCallFunc_Divide_DoubleDouble_ReturnValue_1, double InCallFunc_Add_DoubleDouble_ReturnValue, double InCallFunc_Subtract_DoubleDouble_ReturnValue_2, const struct FVector& InCallFunc_GetVelocity_ReturnValue, const struct FVector& InCallFunc_K2_GetActorLocation_ReturnValue, const struct FVector& InCallFunc_GetVelocity_ReturnValue_1, const struct FVector& InCallFunc_K2_GetActorLocation_ReturnValue_1, const struct FVector& InCallFunc_Subtract_VectorVector_ReturnValue, const struct FVector& InCallFunc_Normal_ReturnValue, double InCallFunc_Dot_VectorVector_ReturnValue, double InCallFunc_Dot_VectorVector_ReturnValue_1);
	void AkSetRTPC(class UAkRtpc* InRTPCValue, double InValue, int32 InInterpolationTimeMs, class AActor* InActor, class UObject* In__WorldContext, const TArray<class UAkComponent*>& InAkComponents, class UComp_RtpcTracker_C* InRtpcTracker, bool InCallFunc_IsValid_ReturnValue, int32 InCallFunc_Array_Length_ReturnValue, TArray<class UAkComponent*>& InCallFunc_K2_GetComponentsByClass_ReturnValue, int32 InCallFunc_Array_Length_ReturnValue_1, bool InCallFunc_Greater_IntInt_ReturnValue, int32 InTemp_int_Array_Index_Variable, class UAkComponent* InCallFunc_Array_Get_Item, int32 InTemp_int_Loop_Counter_Variable, bool InCallFunc_Less_IntInt_ReturnValue, int32 InCallFunc_Add_IntInt_ReturnValue, class UComp_RtpcTracker_C* InCallFunc_GetComponentByClass_ReturnValue, bool InCallFunc_IsValid_ReturnValue_1, float InCallFunc_SetRTPCValue_Value_ImplicitCast, float InCallFunc_SetRTPCValue_Value_ImplicitCast_1, float InCallFunc_SetRTPCValue_Value_ImplicitCast_2);
	void Broadcast_Ak_Event_Location(class AActor* InActorHit, bool InWasDamaged, class AActor* InInstigator, int32 InSearch_Radius, class APlayerController* InPCT_To_Exclude, TSoftObjectPtr<class UVAL_ItemTypeDefinitionAsset> InHeld_ItemType, class UObject* In__WorldContext, double InLocallyControlled, class AValeriaPlayerController* InK2Node_DynamicCast_AsValeria_Player_Controller, bool InK2Node_DynamicCast_bSuccess, const struct FVector& InCallFunc_K2_GetActorLocation_ReturnValue);
	void AkEventSpawnAttached(class UAkAudioEvent* InAkEvent, class AActor* InInstigator, class USceneComponent* InOwner, class FName InSocketName, bool InAutoDestroy, bool InGetRtpcFromOwner, class UObject* In__WorldContext, class UAkComponent** InAK, int32* InID, int32 InPlayingID, class UAkComponent* InAkComponent, double InLocallyControlled, bool InCallFunc_IsDedicatedServer_ReturnValue, bool InCallFunc_IsValid_ReturnValue, class AActor* InCallFunc_GetOwner_ReturnValue, const struct FVector& InCallFunc_K2_GetComponentLocation_ReturnValue, bool InCallFunc_Try_to_Propagate_Rtpcs_Success, const struct FVector& InCallFunc_K2_GetComponentLocation_ReturnValue_1, class APawn* InK2Node_DynamicCast_AsPawn, bool InK2Node_DynamicCast_bSuccess, bool InCallFunc_IsLocallyControlled_ReturnValue, const struct FVector& InCallFunc_GetSocketLocation_ReturnValue, bool InCallFunc_IsWithinAttenuation_Within, FDelegateProperty_ InTemp_delegate_Variable, class UAkComponent* InCallFunc_SpawnAkComponentAtLocation_ReturnValue, bool InCallFunc_K2_AttachToComponent_ReturnValue, TArray<struct FAkExternalSourceInfo>& InTemp_struct_Variable, int32 InCallFunc_PostAkEvent_ReturnValue, float InCallFunc_SetRTPCValue_Value_ImplicitCast);
	void SurfaceDTPM(class AActor* InActor, class UDataTable* InDataTable, class UPhysicalMaterial* InPhysMat, class UObject* In__WorldContext, class UAkAudioEvent** InSound, class UMaterialInstance** InDecal_Left_Foot, class UMaterialInstance** InDecal_Right_Foot, class UNiagaraSystem** InNiagara_System, class FName InDefaultInGamePhysmat, class FName InRowNamePhysmat, enum class EPhysicalSurface InDefaultPhysmatEditorAudition, const class FString& InCallFunc_GetDisplayName_ReturnValue, bool InCallFunc_EqualEqual_StrStr_ReturnValue, bool InCallFunc_EqualEqual_StrStr_ReturnValue_1, bool InCallFunc_EqualEqual_StrStr_ReturnValue_2, const class FString& InCallFunc_RightChop_ReturnValue, bool InCallFunc_BooleanOR_ReturnValue, class FName InCallFunc_Conv_StringToName_ReturnValue, bool InCallFunc_BooleanOR_ReturnValue_1, bool InCallFunc_IsPackagedForDistribution_ReturnValue, bool InCallFunc_Not_PreBool_ReturnValue, const class FString& InCallFunc_GetDisplayName_ReturnValue_1, const class FString& InCallFunc_Concat_StrStr_ReturnValue, const class FString& InCallFunc_Concat_StrStr_ReturnValue_1, bool InCallFunc_EqualEqual_ByteByte_ReturnValue, const class FString& InCallFunc_GetEnumeratorUserFriendlyName_ReturnValue, class FName InCallFunc_Conv_StringToName_ReturnValue_1, const struct FStruct_Physmat& InCallFunc_GetDataTableRowFromName_OutRow, bool InCallFunc_GetDataTableRowFromName_ReturnValue, const class FString& InCallFunc_Conv_NameToString_ReturnValue, const class FString& InCallFunc_Concat_StrStr_ReturnValue_2, class UGameInstance* InCallFunc_GetGameInstance_ReturnValue, bool InCallFunc_IsValid_ReturnValue);
	void Surface_DT(class AActor* InActor, class UDataTable* InDataTable, class UPhysicalMaterial* InPhysMat, class UObject* In__WorldContext, class UAkAudioEvent** InSound, class UMaterialInstance** InDecal_Left_Foot, class UMaterialInstance** InDecal_Right_Foot, class UNiagaraSystem** InNiagaraSystem, class UNiagaraSystem* InNS, enum class E_Footwear InFootwearDebug, class FName InFootwear, class UMaterialInstance* InDR, class UMaterialInstance* InDL, class UAkAudioEvent* InS, class FName InRowNamePhysmat, enum class EPhysicalSurface InDefaultPhysmatEditorAudition, enum class EPhysicalSurface InDefaultPhysmatInGame, const class FString& InCallFunc_GetEnumeratorUserFriendlyName_ReturnValue, class FName InCallFunc_Conv_StringToName_ReturnValue, class UComp_Actor_Audio_Data_C* InCallFunc_GetComponentByClass_ReturnValue, bool InCallFunc_IsValid_ReturnValue, const class FString& InCallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1, class FName InCallFunc_Conv_StringToName_ReturnValue_1, const struct FStruct_Footwear& InCallFunc_GetDataTableRowFromName_OutRow, bool InCallFunc_GetDataTableRowFromName_ReturnValue, const class FString& InCallFunc_GetObjectName_ReturnValue, const class FString& InCallFunc_Left_ReturnValue, bool InK2Node_SwitchString_CmpSuccess, class UAkAudioEvent* InCallFunc_SurfaceDTPM_Sound, class UMaterialInstance* InCallFunc_SurfaceDTPM_Decal_Left_Foot, class UMaterialInstance* InCallFunc_SurfaceDTPM_Decal_Right_Foot, class UNiagaraSystem* InCallFunc_SurfaceDTPM_Niagara_System, class UAkAudioEvent* InCallFunc_SurfaceDTPM_Sound_1, class UMaterialInstance* InCallFunc_SurfaceDTPM_Decal_Left_Foot_1, class UMaterialInstance* InCallFunc_SurfaceDTPM_Decal_Right_Foot_1, class UNiagaraSystem* InCallFunc_SurfaceDTPM_Niagara_System_1);
	void IsWithinAttenuation(class UAkAudioEvent* InEvent, const struct FVector& InLocation, class UObject* In__WorldContext, bool* InWithin, bool InCallFunc_VIsWithinAttenuation_ReturnValue);
	void AkEventLocationWithActor(class UAkAudioEvent* InAkEvent, const struct FVector& InLocation, class AActor* InActor, bool InGetRtpcFromActor, class UObject* In__WorldContext, class UAkComponent** InAkComponent, int32* InPlaying_ID, class UAkComponent* InAkComp, double InLocallyControlled, bool InCallFunc_IsDedicatedServer_ReturnValue, FDelegateProperty_ InTemp_delegate_Variable, bool InCallFunc_Try_to_Propagate_Rtpcs_Success, class APawn* InK2Node_DynamicCast_AsPawn, bool InK2Node_DynamicCast_bSuccess, bool InCallFunc_IsValid_ReturnValue, bool InCallFunc_IsLocallyControlled_ReturnValue, bool InCallFunc_IsLocallyControlled_ReturnValue_1, class UAkComponent* InCallFunc_AkSpawnAtLocation_ReturnValue, TArray<struct FAkExternalSourceInfo>& InTemp_struct_Variable, int32 InCallFunc_PostAkEvent_ReturnValue, bool InCallFunc_IsWithinAttenuation_Within, bool InCallFunc_IsValid_ReturnValue_1, float InCallFunc_SetRTPCValue_Value_ImplicitCast);
	void AkEventLocation(class UAkAudioEvent* InAkEvent, const struct FVector& InLocation, class AActor* InInstigator, bool InGetRtpcsFromInstigator, class UObject* In__WorldContext, class UAkComponent** InAkComponent, int32* InPlaying_ID, int32 InPlayingID, class UAkComponent* InAkComp, double InLocallyControlled, class UAkComponent* InCallFunc_VAkEventLocation_OutComponent, int32 InCallFunc_VAkEventLocation_ReturnValue, bool InCallFunc_Try_to_Propagate_Rtpcs_Success);
	int32 AkEventComponentCallback(class UAkAudioEvent* InAkEvent, class UAkComponent* InAkComponent, int32 InCallbackMask, FDelegateProperty_& InPostEventCallback, bool InCheckAttenuation, bool InGetRtpcFromOwner, class UObject* In__WorldContext, double InLocallyControlled, bool InCallFunc_IsDedicatedServer_ReturnValue, class AActor* InCallFunc_GetOwner_ReturnValue, bool InCallFunc_Try_to_Propagate_Rtpcs_Success, bool InCallFunc_GetAutoDestroy_ReturnValue, class AActor* InCallFunc_GetOwner_ReturnValue_1, class APawn* InK2Node_DynamicCast_AsPawn, bool InK2Node_DynamicCast_bSuccess, bool InCallFunc_IsLocallyControlled_ReturnValue, bool InCallFunc_IsValid_ReturnValue, bool InCallFunc_IsLocallyControlled_ReturnValue_1, bool InCallFunc_IsValid_ReturnValue_1, const struct FVector& InCallFunc_K2_GetComponentLocation_ReturnValue, bool InCallFunc_VIsWithinAttenuation_ReturnValue, TArray<struct FAkExternalSourceInfo>& InTemp_struct_Variable, bool InCallFunc_IsValid_ReturnValue_2, int32 InCallFunc_PostAkEvent_ReturnValue, float InCallFunc_SetRTPCValue_Value_ImplicitCast);
	int32 AkEventComponent(class UAkAudioEvent* InAkEvent, class UAkComponent* InAkComponent, bool InGetRtpcFromOwner, class UObject* In__WorldContext, double InLocallyControlled, class AActor* InCallFunc_GetOwner_ReturnValue, int32 InCallFunc_VAkEventComponent_ReturnValue, bool InCallFunc_Try_to_Propagate_Rtpcs_Success);
	int32 AkEventActor(class UAkAudioEvent* InAkEvent, class AActor* InActor, class UObject* In__WorldContext, double InLocallyControlled, bool InCallFunc_IsDedicatedServer_ReturnValue, class APawn* InK2Node_DynamicCast_AsPawn, bool InK2Node_DynamicCast_bSuccess, bool InCallFunc_IsLocallyControlled_ReturnValue, class USceneComponent* InCallFunc_K2_GetRootComponent_ReturnValue, bool InCallFunc_AkGetComponent_ComponentCreated, class UAkComponent* InCallFunc_AkGetComponent_AkComponent, bool InCallFunc_Try_to_Propagate_Rtpcs_Success, bool InCallFunc_IsValid_ReturnValue, bool InCallFunc_IsLocallyControlled_ReturnValue_1, bool InCallFunc_IsValid_ReturnValue_1, FDelegateProperty_ InTemp_delegate_Variable, TArray<struct FAkExternalSourceInfo>& InTemp_struct_Variable, int32 InCallFunc_PostAkEvent_ReturnValue, const struct FVector& InCallFunc_K2_GetActorLocation_ReturnValue, bool InCallFunc_IsWithinAttenuation_Within, bool InCallFunc_IsValid_ReturnValue_2);
	int32 AkEventGlobal(class UAkAudioEvent* InAkEvent, class UObject* In__WorldContext, bool InCallFunc_IsDedicatedServer_ReturnValue, bool InCallFunc_IsValid_ReturnValue, int32 InCallFunc_PostGlobalEvent_ReturnValue);
	void Ak_Object_Velocity(class UAkComponent* InAK, double InVectorLengthMax, double InDelta_Time, const struct FVector& InGet_Previous_Location, int32 InInterpTimeMs, class UObject* In__WorldContext, struct FVector* InSet_Previous_Location, double* InVectorLength, double* InVectorLengthClamped, class FName InObject_velocity, double InVectorMax, bool InCallFunc_IsDedicatedServer_ReturnValue, const struct FVector& InCallFunc_K2_GetComponentLocation_ReturnValue, const struct FVector& InCallFunc_K2_GetComponentLocation_ReturnValue_1, const struct FVector& InCallFunc_Subtract_VectorVector_ReturnValue, double InCallFunc_VSize_ReturnValue, double InCallFunc_Divide_DoubleDouble_ReturnValue, double InCallFunc_MapRangeClamped_ReturnValue, bool InCallFunc_IsValid_ReturnValue, float InCallFunc_SetRTPCValue_Value_ImplicitCast);
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
