#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x0 (0x28 - 0x28)
// BlueprintGeneratedClass Lib_Audio.Lib_Audio_C
class ULib_Audio_C : public UBlueprintFunctionLibrary
{
public:

	static class UClass* StaticClass();
	static class ULib_Audio_C* GetDefaultObj();

	void GetMusicManager(class UObject* __WorldContext, class UBP_MusicManager_C** AsBP_Music_Manager, class UGameInstance* CallFunc_GetGameInstance_ReturnValue, class UValeriaGameInstance* K2Node_DynamicCast_AsValeria_Game_Instance, bool K2Node_DynamicCast_bSuccess, class UMusicManager* CallFunc_GetMusicManager_ReturnValue, class UBP_MusicManager_C* K2Node_DynamicCast_AsBP_Music_Manager, bool K2Node_DynamicCast_bSuccess_1);
	void Try_to_Propagate_Rtpcs(class AActor* Actor, class UAkComponent* AkComponent, class UObject* __WorldContext, bool* Success, class UComp_RtpcTracker_C* Tracker, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UComp_RtpcTracker_C* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_2);
	void AkGetComponent(class USceneComponent* AttachToComponent, class FName AttachPointName, const struct FVector& Location, enum class EAttachLocation LocationType, bool bAutoDestroy, class UObject* __WorldContext, bool* ComponentCreated, class UAkComponent** AkComponent, bool CallFunc_VAkGetComponent_ComponentCreated, class UAkComponent* CallFunc_VAkGetComponent_ReturnValue);
	void AkExecuteActionOnPlayingID(enum class EAkActionOnEventType ActionType, int32 PlayingID, int32 TransitionDuration, enum class EAkCurveInterpolation FadeCurve, class UObject* __WorldContext);
	void IsInside(const struct FVector& Location, class UObject* __WorldContext, bool* IsInside, bool Inside, bool Temp_bool_True_if_break_was_hit_Variable, class UAkRoomComponent* CallFunc_GetAkAudioRoomAtLocation_HighestPriorityRoom, TArray<class UAkRoomComponent*>& CallFunc_GetAkAudioRoomAtLocation_AllRooms, bool CallFunc_IsValid_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, class AAkSpatialAudioVolume* K2Node_DynamicCast_AsAk_Spatial_Audio_Volume, bool K2Node_DynamicCast_bSuccess, TArray<class UComp_CV_Local_RTPC_C*>& CallFunc_K2_GetComponentsByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Array_Index_Variable, class UComp_CV_Local_RTPC_C* CallFunc_Array_Get_Item, bool CallFunc_EqualEqual_DoubleDouble_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1);
	void IsWet(const struct FVector& Location, class UObject* __WorldContext, bool* IsWet, class UValeriaWeather* CallFunc_GetWorldSubsystem_ReturnValue, bool CallFunc_IsInside_IsInside, const struct FWeatherStateProperties& CallFunc_GetCurrentWorldWeatherState_ReturnValue, bool CallFunc_HasTag_ReturnValue);
	void AkCulledAssignAndStart(class UAkAudioEvent* AkEvent, class UAkCulledComponent* AkCulledComponent, class UObject* __WorldContext, double LocallyControlled, bool CallFunc_IsDedicatedServer_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void GetAkAudioRoomAtLocation(const struct FVector& Location, class UObject* __WorldContext, class UAkRoomComponent** HighestPriorityRoom, TArray<class UAkRoomComponent*>* AllRooms, const TArray<class UAkRoomComponent*>& LRoomComponents, class UAkRoomComponent* LHighestPriorityRoom, double LHighestPriority, int32 Temp_int_Loop_Counter_Variable, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_2, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Array_Index_Variable_2, int32 Temp_int_Loop_Counter_Variable_3, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 Temp_int_Array_Index_Variable_3, class UAkRoomComponent* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, TArray<class AActor*>& Temp_object_Variable, TArray<class AActor*>& Temp_object_Variable_1, TArray<enum class EObjectTypeQuery>& K2Node_MakeArray_Array, TArray<class UPrimitiveComponent*>& CallFunc_SphereOverlapComponents_OutComponents, bool CallFunc_SphereOverlapComponents_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue, class UPrimitiveComponent* CallFunc_Array_Get_Item_1, TArray<class USceneComponent*>& CallFunc_GetChildrenComponents_Children, int32 CallFunc_Array_Length_ReturnValue_1, class USceneComponent* CallFunc_Array_Get_Item_2, bool CallFunc_Less_IntInt_ReturnValue_1, class UAkRoomComponent* K2Node_DynamicCast_AsAk_Room_Component, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_AddUnique_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, TArray<class AActor*>& CallFunc_SphereOverlapActors_OutActors, bool CallFunc_SphereOverlapActors_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_2, class AActor* CallFunc_Array_Get_Item_3, class AValeriaSpatialAudioVolume* K2Node_DynamicCast_AsValeria_Spatial_Audio_Volume, bool K2Node_DynamicCast_bSuccess_1, int32 CallFunc_Array_Length_ReturnValue_3, bool CallFunc_Less_IntInt_ReturnValue_3, int32 CallFunc_Array_AddUnique_ReturnValue_1, double CallFunc_Greater_DoubleDouble_A_ImplicitCast, double K2Node_VariableSet_LHighestPriority_ImplicitCast);
	int32 PlayTempBeep(bool Global, const struct FVector& Location, class UObject* __WorldContext, bool CallFunc_BuildIsShipping_ReturnValue, class UAkComponent* CallFunc_AkEventLocation_AkComponent, int32 CallFunc_AkEventLocation_Playing_ID, int32 CallFunc_AkEventGlobal_ReturnValue);
	void LoadAudioUserSettings(class UObject* __WorldContext, class UAkStateValue* Temp_object_Variable, class UAkStateValue* Temp_object_Variable_1, class UAkStateValue* Temp_object_Variable_2, enum class EAudioMixProfiles Temp_byte_Variable, class UValeriaGameUserSettings* CallFunc_GetValeriaGameUserSettings_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UAkStateValue* K2Node_Select_Default, double CallFunc_AkSetRTPC_Value_ImplicitCast, double CallFunc_AkSetRTPC_Value_ImplicitCast_1, double CallFunc_AkSetRTPC_Value_ImplicitCast_2, double CallFunc_AkSetRTPC_Value_ImplicitCast_3);
	void Ak_Music_Switch(class UAkSwitchValue* SwitchValue, bool IgnoreTimeOfDay, class UObject* __WorldContext, bool CallFunc_IsDedicatedServer_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue, class UBP_MusicManager_C* CallFunc_GetMusicManager_AsBP_Music_Manager, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UComp_Listener_Padding_C* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_Not_PreBool_ReturnValue);
	void FindClosestVector(TArray<struct FVector>& InVectors, const struct FVector& ReferencePoint, class UObject* __WorldContext, struct FVector* ClosestVector, int32* Index, double IterateDistance, int32 ClosestInd, const struct FVector& ClosestVect, double Distance, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Length_ReturnValue, const struct FVector& CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_Less_DoubleDouble_ReturnValue, double CallFunc_Vector_Distance_ReturnValue);
	void GetDopplerPitchMultiplier(class AActor* Listener, class AActor* Object, double DopplerIntensity, class UObject* __WorldContext, double* PitchMultiplier, double FinalPitchScale, double PitchScale, double DopplerPitchScale, double ListenerVelocityMagnitude, double SourceVelocityMagnitude, double CallFunc_Divide_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue_1, double CallFunc_Multiply_DoubleDouble_ReturnValue, double CallFunc_Divide_DoubleDouble_ReturnValue_1, double CallFunc_Add_DoubleDouble_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue_2, const struct FVector& CallFunc_GetVelocity_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FVector& CallFunc_GetVelocity_ReturnValue_1, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue_1, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue, const struct FVector& CallFunc_Normal_ReturnValue, double CallFunc_Dot_VectorVector_ReturnValue, double CallFunc_Dot_VectorVector_ReturnValue_1);
	void AkSetRTPC(class UAkRtpc* RTPCValue, double Value, int32 InterpolationTimeMs, class AActor* Actor, class UObject* __WorldContext, const TArray<class UAkComponent*>& AkComponents, class UComp_RtpcTracker_C* RtpcTracker, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, TArray<class UAkComponent*>& CallFunc_K2_GetComponentsByClass_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, class UAkComponent* CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class UComp_RtpcTracker_C* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, float CallFunc_SetRTPCValue_Value_ImplicitCast, float CallFunc_SetRTPCValue_Value_ImplicitCast_1, float CallFunc_SetRTPCValue_Value_ImplicitCast_2);
	void Broadcast_Ak_Event_Location(class AActor* ActorHit, bool WasDamaged, class AActor* Instigator, int32 Search_Radius, class APlayerController* PCT_To_Exclude, TSoftObjectPtr<class UVAL_ItemTypeDefinitionAsset> Held_ItemType, class UObject* __WorldContext, double LocallyControlled, class AValeriaPlayerController* K2Node_DynamicCast_AsValeria_Player_Controller, bool K2Node_DynamicCast_bSuccess, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue);
	void AkEventSpawnAttached(class UAkAudioEvent* AkEvent, class AActor* Instigator, class USceneComponent* Owner, class FName SocketName, bool AutoDestroy, bool GetRtpcFromOwner, class UObject* __WorldContext, class UAkComponent** Ak, int32* ID, int32 PlayingID, class UAkComponent* AkComponent, double LocallyControlled, bool CallFunc_IsDedicatedServer_ReturnValue, bool CallFunc_IsValid_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, const struct FVector& CallFunc_K2_GetComponentLocation_ReturnValue, bool CallFunc_Try_to_Propagate_Rtpcs_Success, const struct FVector& CallFunc_K2_GetComponentLocation_ReturnValue_1, class APawn* K2Node_DynamicCast_AsPawn, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsLocallyControlled_ReturnValue, const struct FVector& CallFunc_GetSocketLocation_ReturnValue, bool CallFunc_IsWithinAttenuation_Within, FDelegateProperty_ Temp_delegate_Variable, class UAkComponent* CallFunc_SpawnAkComponentAtLocation_ReturnValue, bool CallFunc_K2_AttachToComponent_ReturnValue, TArray<struct FAkExternalSourceInfo>& Temp_struct_Variable, int32 CallFunc_PostAkEvent_ReturnValue, float CallFunc_SetRTPCValue_Value_ImplicitCast);
	void SurfaceDTPM(class AActor* Actor, class UDataTable* DataTable, class UPhysicalMaterial* PhysMat, class UObject* __WorldContext, class UAkAudioEvent** Sound, class UMaterialInstance** Decal_Left_Foot, class UMaterialInstance** Decal_Right_Foot, class UNiagaraSystem** Niagara_System, class FName DefaultInGamePhysmat, class FName RowNamePhysmat, enum class EPhysicalSurface DefaultPhysmatEditorAudition, const class FString& CallFunc_GetDisplayName_ReturnValue, bool CallFunc_EqualEqual_StrStr_ReturnValue, bool CallFunc_EqualEqual_StrStr_ReturnValue_1, bool CallFunc_EqualEqual_StrStr_ReturnValue_2, const class FString& CallFunc_RightChop_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, class FName CallFunc_Conv_StringToName_ReturnValue, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_IsPackagedForDistribution_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, const class FString& CallFunc_GetDisplayName_ReturnValue_1, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue, const class FString& CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, class FName CallFunc_Conv_StringToName_ReturnValue_1, const struct FStruct_Physmat& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, class UGameInstance* CallFunc_GetGameInstance_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void Surface_DT(class AActor* Actor, class UDataTable* DataTable, class UPhysicalMaterial* PhysMat, class UObject* __WorldContext, class UAkAudioEvent** Sound, class UMaterialInstance** Decal_Left_Foot, class UMaterialInstance** Decal_Right_Foot, class UNiagaraSystem** NiagaraSystem, class UNiagaraSystem* NS, enum class E_Footwear FootwearDebug, class FName Footwear, class UMaterialInstance* DR, class UMaterialInstance* DL, class UAkAudioEvent* S, class FName RowNamePhysmat, enum class EPhysicalSurface DefaultPhysmatEditorAudition, enum class EPhysicalSurface DefaultPhysmatInGame, const class FString& CallFunc_GetEnumeratorUserFriendlyName_ReturnValue, class FName CallFunc_Conv_StringToName_ReturnValue, class UComp_Actor_Audio_Data_C* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, const class FString& CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1, class FName CallFunc_Conv_StringToName_ReturnValue_1, const struct FStruct_Footwear& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, const class FString& CallFunc_GetObjectName_ReturnValue, const class FString& CallFunc_Left_ReturnValue, bool K2Node_SwitchString_CmpSuccess, class UAkAudioEvent* CallFunc_SurfaceDTPM_Sound, class UMaterialInstance* CallFunc_SurfaceDTPM_Decal_Left_Foot, class UMaterialInstance* CallFunc_SurfaceDTPM_Decal_Right_Foot, class UNiagaraSystem* CallFunc_SurfaceDTPM_Niagara_System, class UAkAudioEvent* CallFunc_SurfaceDTPM_Sound_1, class UMaterialInstance* CallFunc_SurfaceDTPM_Decal_Left_Foot_1, class UMaterialInstance* CallFunc_SurfaceDTPM_Decal_Right_Foot_1, class UNiagaraSystem* CallFunc_SurfaceDTPM_Niagara_System_1);
	void IsWithinAttenuation(class UAkAudioEvent* Event, const struct FVector& Location, class UObject* __WorldContext, bool* Within, bool CallFunc_VIsWithinAttenuation_ReturnValue);
	void AkEventLocationWithActor(class UAkAudioEvent* AkEvent, const struct FVector& Location, class AActor* Actor, bool GetRtpcFromActor, class UObject* __WorldContext, class UAkComponent** AkComponent, int32* Playing_ID, class UAkComponent* AkComp, double LocallyControlled, bool CallFunc_IsDedicatedServer_ReturnValue, FDelegateProperty_ Temp_delegate_Variable, bool CallFunc_Try_to_Propagate_Rtpcs_Success, class APawn* K2Node_DynamicCast_AsPawn, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsLocallyControlled_ReturnValue, bool CallFunc_IsLocallyControlled_ReturnValue_1, class UAkComponent* CallFunc_AkSpawnAtLocation_ReturnValue, TArray<struct FAkExternalSourceInfo>& Temp_struct_Variable, int32 CallFunc_PostAkEvent_ReturnValue, bool CallFunc_IsWithinAttenuation_Within, bool CallFunc_IsValid_ReturnValue_1, float CallFunc_SetRTPCValue_Value_ImplicitCast);
	void AkEventLocation(class UAkAudioEvent* AkEvent, const struct FVector& Location, class AActor* Instigator, bool GetRtpcsFromInstigator, class UObject* __WorldContext, class UAkComponent** AkComponent, int32* Playing_ID, int32 PlayingID, class UAkComponent* AkComp, double LocallyControlled, class UAkComponent* CallFunc_VAkEventLocation_OutComponent, int32 CallFunc_VAkEventLocation_ReturnValue, bool CallFunc_Try_to_Propagate_Rtpcs_Success);
	int32 AkEventComponentCallback(class UAkAudioEvent* AkEvent, class UAkComponent* AkComponent, int32 CallbackMask, FDelegateProperty_& PostEventCallback, bool CheckAttenuation, bool GetRtpcFromOwner, class UObject* __WorldContext, double LocallyControlled, bool CallFunc_IsDedicatedServer_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_Try_to_Propagate_Rtpcs_Success, bool CallFunc_GetAutoDestroy_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, class APawn* K2Node_DynamicCast_AsPawn, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsLocallyControlled_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsLocallyControlled_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, const struct FVector& CallFunc_K2_GetComponentLocation_ReturnValue, bool CallFunc_VIsWithinAttenuation_ReturnValue, TArray<struct FAkExternalSourceInfo>& Temp_struct_Variable, bool CallFunc_IsValid_ReturnValue_2, int32 CallFunc_PostAkEvent_ReturnValue, float CallFunc_SetRTPCValue_Value_ImplicitCast);
	int32 AkEventComponent(class UAkAudioEvent* AkEvent, class UAkComponent* AkComponent, bool GetRtpcFromOwner, class UObject* __WorldContext, double LocallyControlled, class AActor* CallFunc_GetOwner_ReturnValue, int32 CallFunc_VAkEventComponent_ReturnValue, bool CallFunc_Try_to_Propagate_Rtpcs_Success);
	int32 AkEventActor(class UAkAudioEvent* AkEvent, class AActor* Actor, class UObject* __WorldContext, double LocallyControlled, bool CallFunc_IsDedicatedServer_ReturnValue, class APawn* K2Node_DynamicCast_AsPawn, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsLocallyControlled_ReturnValue, class USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue, bool CallFunc_AkGetComponent_ComponentCreated, class UAkComponent* CallFunc_AkGetComponent_AkComponent, bool CallFunc_Try_to_Propagate_Rtpcs_Success, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsLocallyControlled_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, FDelegateProperty_ Temp_delegate_Variable, TArray<struct FAkExternalSourceInfo>& Temp_struct_Variable, int32 CallFunc_PostAkEvent_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_IsWithinAttenuation_Within, bool CallFunc_IsValid_ReturnValue_2);
	int32 AkEventGlobal(class UAkAudioEvent* AkEvent, class UObject* __WorldContext, bool CallFunc_IsDedicatedServer_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_PostGlobalEvent_ReturnValue);
	void Ak_Object_Velocity(class UAkComponent* Ak, double VectorLengthMax, double Delta_Time, const struct FVector& Get_Previous_Location, int32 InterpTimeMs, class UObject* __WorldContext, struct FVector* Set_Previous_Location, double* VectorLength, double* VectorLengthClamped, double LengthClamped, double Length, class FName Object_velocity, double VectorMax, bool CallFunc_IsDedicatedServer_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FVector& CallFunc_K2_GetComponentLocation_ReturnValue, const struct FVector& CallFunc_K2_GetComponentLocation_ReturnValue_1, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue, double CallFunc_VSize_ReturnValue, double CallFunc_MapRangeClamped_ReturnValue, double CallFunc_Divide_DoubleDouble_ReturnValue, float CallFunc_SetRTPCValue_Value_ImplicitCast);
};

}


